# Generated by Django 5.1.3 on 2024-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
