# Generated by Django 5.1.3 on 2024-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0002_alter_personaldata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
