# Generated by Django 5.1.3 on 2024-11-25 12:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0003_biography_active_personaldata_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TechnicalProtfolio',
            new_name='TeachingProtfolio',
        ),
    ]
