# Generated by Django 5.1.3 on 2024-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0005_personaldata_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('GitHub', 'GitHub'), ('GitLab', 'GitLab'), ('Bitbucket', 'Bitbucket'), ('StackOverflow', 'StackOverflow'), ('ResearchGate', 'ResearchGate'), ('GoogleScholar', 'GoogleScholar'), ('CodeForces', 'CodeForces'), ('LeetCode', 'LeetCode'), ('Kaggle', 'Kaggle'), ('YouTube', 'YouTube'), ('HackerRank', 'HackerRank')], max_length=100),
        ),
    ]
